Attempts to succeed on older equipment and or i386 C libs only.

diff --git a/example/initramfs/hooks/vdev b/example/initramfs/hooks/vdev
--- a/example/initramfs/hooks/vdev
+++ b/example/initramfs/hooks/vdev
@@ -1,5 +1,7 @@
 #!/bin/sh -e
 
+## set -x
+
 PREREQS=""
 
 prereqs() { echo "$PREREQS"; }
@@ -11,28 +13,36 @@ case "$1" in
     ;;
 esac
 
-. /usr/share/initramfs-tools/hook-functions
+. /usr/share/initramfs-tools/hook-functions 
+
+# Needed for keyboard
+
+force_load evdev || echo "eventfs (mod evdev ?) not preloaded" && sleep 2
 
 # helper programs
-mkdir -p $DESTDIR/lib/vdev
+
+mkdir -vp $DESTDIR/lib/vdev 
+
 for prog in /lib/vdev/*; do
 
    # shell script or library?
    if [ -z "${prog#*.sh}" ]; then 
-
       cp -a $prog $DESTDIR/lib/vdev/
    else
-
       # binary?
       if [ -f $prog -a -x $prog ]; then 
-
          copy_exec $prog /lib/vdev
       fi
    fi
 done
 
+# libudev-compat
+if [ -f /lib/libudev.so.1 ] ; then
+    copy_exec /lib/libudev.so.1
+fi
+
 # config 
-mkdir -p $DESTDIR/etc/vdev
+mkdir -pv $DESTDIR/etc/vdev
 cp -a /etc/vdev/* $DESTDIR/etc/vdev/
 
 # the daemon itself 
@@ -63,19 +73,28 @@ if [ -f /sbin/lvm ]; then
 else
    echo "WARN: could not find lvm in /sbin/lvm.  Logical volume symlinks will not be created."
 fi
-
+#
 # network tools (needed by vdevd's helpers)
+# busy box may provide alternatives
+# for human uses. (?)
+#
+if ! [ -f /sbin/ip ] && ! [ -f /bin/ip ]; then 
+    echo "WARN: could not find iproute2 in /bin/ip or /sbin/ip."
+    echo "Network interfaces will not be configured."
+fi
+
 if [ -f /bin/ip ]; then
    copy_exec /bin/ip
 fi
 
 if [ -f /sbin/ip ]; then 
    copy_exec /sbin/ip
+else [ -f /sbin/ifconfig ]; then
+# try the classical tool
+    copy_exec /sbin/ifconfig 
+    echo "installing /sbin/ifconfig as networking tool"
 fi
 
-if ! [ -f /sbin/ip ] && ! [ -f /bin/ip ]; then 
-   echo "WARN: could not find iproute2 in /bin/ip or /sbin/ip.  Network interfaces will not be configured."
-fi
 
 # SELinux tools
 if [ -f /sbin/restorecon ]; then 
@@ -84,7 +103,10 @@ fi
 
 # device tools
 if [ -f /sbin/MAKEDEV ]; then 
-   copy_exec /sbin/MAKEDEV || true
+    copy_exec /sbin/MAKEDEV
+else
+    echo "WARNING: No MAKEDEV found to install"
+    echo "vdev --once    may be your best alterenative"
 fi
 
 # device mapper tools
@@ -96,10 +118,12 @@ fi
 
 # hardware database 
 if [ -f /lib/vdev/hwdb/hwdb.squashfs ]; then 
+   copy_exec /sbin/losetup
    mkdir -p $DESTDIR/lib/vdev/hwdb
    cp -a /lib/vdev/hwdb/hwdb.squashfs $DESTDIR/lib/vdev/hwdb
 else
-   echo "WARN: could not find hardware database in /lib/vdev/hwdb.  Some hardware metadata may not be generated."
+    echo "WARN: could not find hardware database in /lib/vdev/hwdb.  Some hardware metadata may not be generated."
+    sleep 2
 fi
 
 # GNU tools (not the busybox equivalents)
@@ -112,19 +136,42 @@ copy_exec /bin/egrep
 copy_exec /bin/kmod 
 
 # users and groups databases
-cp -a /etc/passwd $DESTDIR/etc/passwd
-cp -a /etc/group $DESTDIR/etc/group
+cp -va /etc/passwd $DESTDIR/etc/passwd
+cp -va /etc/group $DESTDIR/etc/group
 
-# extra libc goodies 
-copy_exec /lib/x86_64-linux-gnu/libc.so.6
-copy_exec /lib/x86_64-linux-gnu/libnss_compat.so.2
-copy_exec /lib/x86_64-linux-gnu/libnsl.so.1
-copy_exec /lib/x86_64-linux-gnu/libnss_nis.so.2
-copy_exec /lib/x86_64-linux-gnu/libnss_files.so.2
+#
+# extra libc goodies
+# Falling to i386 if i686 is the uname machine type
+# and the i686 libc version is not found.
+# 
+#
+if [ -d /lib/$(arch)-linux-gnu ]; then
+    LIBC=/lib/$(arch)-linux-gnu
+elif [ -d /lib/i386-linux-gnu ]; then
+    LIBC=/lib/i386-linux-gnu
+else
+    # make noise and trigger -e if set
+    echo "Unable to find libc shared object files for $(arch)"
+    sleep 1
+    echo "Please check dependancies or package install order"
+    sleep 2
+    /bin/false
+fi
 
-# since vdevd is multi-threaded, libpthread will dynamically load libgcc_s
+copy_exec $LIBC/libc.so.6 || echo "$LIBC/libc.so.6 (still) not found"  
+copy_exec $LIBC/libnss_compat.so.2 
+copy_exec $LIBC/libnsl.so.1
+copy_exec $LIBC/libnss_nis.so.2
+copy_exec $LIBC/libnss_files.so.2
+#
+# since vdevd is multi-threaded,
+# libpthread will need to dynamically load libgcc_s
 # (and copy_exec won't detect this)
-copy_exec /lib/`gcc -print-multiarch`/libgcc_s.so.1
+#
+copy_exec $LIBC/libgcc_s.so.1 || echo "libpthread needs libgcc_s"
 
 # until we're confident that the scripts work with busybox's sh, use dash
 copy_exec /bin/dash
+
+# be polite
+exit 
